CREATE TABLE IF NOT EXISTS location (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT NOT NULL COLLATE NOCASE
);

DROP TABLE entry;
DROP TABLE person;
DROP TABLE horse;
DROP TABLE race;
DROP TABLE pending_entry;
DROP TABLE pending_race;

CREATE TABLE IF NOT EXISTS race (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
location_id INTEGER NOT NULL REFERENCES location(_id),
started INTEGER NOT NULL, --off time
race_number INTEGER NOT NULL,
purse INTEGER DEFAULT NULL, --cents
gait TEXT DEFAULT NULL COLLATE NOCASE,
race_class TEXT DEFAULT NULL COLLATE NOCASE,
conditions TEXT DEFAULT NULL COLLATE NOCASE,
distance REAL DEFAULT NULL,
temp INTEGER DEFAULT NULL,
allow INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS horse (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
name TEXT NOT NULL COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS person (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
firstname TEXT NOT NULL COLLATE NOCASE,
middle TEXT DEFAULT NULL COLLATE NOCASE,
lastname TEXT NOT NULL COLLATE NOCASE
);

CREATE TABLE IF NOT EXISTS entry (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
race_id INTEGER NOT NULL REFERENCES race(_id),
horse_id INTEGER NOT NULL REFERENCES horse(_id),
driver_id INTEGER NOT NULL REFERENCES person(_id),
trainer_id INTEGER NOT NULL REFERENCES person(_id),
horse_number INTEGER NOT NULL,
post_position TEXT DEFAULT NULL,
finish_position INTEGER DEFAULT NULL,
time INTEGER DEFAULT NULL,
time_last_quarter INTEGER DEFAULT NULL,
odds REAL DEFAULT NULL,
meds TEXT DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS pending_race (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
location_id INTEGER NOT NULL REFERENCES location(_id),
scheduled INTEGER NOT NULL, --off time
race_number INTEGER NOT NULL,
purse INTEGER DEFAULT NULL, --cents
gait TEXT DEFAULT NULL COLLATE NOCASE,
race_class TEXT DEFAULT NULL COLLATE NOCASE,
distance REAL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS pending_entry (
_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
race_id INTEGER NOT NULL REFERENCES pending_race(_id),
horse_id INTEGER NOT NULL REFERENCES horse(_id),
driver_id INTEGER DEFAULT NULL REFERENCES person(_id),
trainer_id INTEGER NOT NULL REFERENCES person(_id),
horse_number INTEGER NOT NULL,
post_position TEXT DEFAULT NULL,
claiming INTEGER DEFAULT NULL, --cents
odds REAL DEFAULT NULL,
meds TEXT DEFAULT NULL
);

